### ISSUE TITLE
Keyboard Plugin Issue

### ISSUE THREAD

**Issue by milos-zivanovic** [NikolaDavidovic/womans#1]
Hey Nikola,

during my work on a map page, i notice an issue in firebug with keyboard plugin for jQuery.
For the reason that you implement this plugin, i`m assigning you to check this.
Below you should see a screenshot.

Tnx

![screenshot from 2016-10-25 03-56-42](https://cloud.githubusercontent.com/assets/22960594/19670451/9d2a996e-9a67-11e6-9a68-43df1593928b.png)

**Comment by milos-zivanovic** [comment]
Everything is working fine for now.
But i`m wondering about issues which might occure later (during the test on some devices, tablets etc)

**Comment by NikolaDavidovic** [comment]
Hey Milos,

This is fixed.

Nikola
